# Site Settings
title: Wyatt's Blog
email: wkellett@wustl.edu
description: >-
  Student at Washington University in St. Louis, majoring in Computer Science and Applied Mathematics. I like to just mess around here.
baseurl: ""
url: "http://wyatt00.github.io"
twitter_username: wyattkellett
instagram_username: wyattkellett
github_username: wyatt00

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
